### ISSUE TITLE
Filter Alignment issue (20/02/12 version)

### ISSUE THREAD

**Issue by SadE54** [gallickgunner/ImGui-Addons#11]
Hi , 

I'm using the extension on Windows , and I get this opening the file dialog : 
![filebrowserproblem](https://user-images.githubusercontent.com/2878768/74310408-70f37980-4d6d-11ea-8458-58c30e965867.png)
As you can see there's a small alignment problem of the filter that is behind the file list.
Anyway thanks for your work ! Until now it's the best file browser for imgui windows users :)

**Comment by SadE54** [comment]
As a personal  suggestion , may I would remove (at least visually) the blue box from the dir chained list.

**Comment by SadE54** [comment]
The filter alignment problem  exists only for the open dialog , not the 'save' one.
And I forgot to mention the 'Cancel' button that is not long enough.

**Comment by bwrsandman** [comment]
I ran into this and the solution is probably to take into account `style.ItemSpacing`

**Comment by gallickgunner** [comment]
I'm glad you liked it. Can you tell me what's the size parameter you are passing to `OpenFileDialog` ? As far as I remember I had solved this, so on providing smaller sizes for the file dialog the window that renders the files and directories shrinks accordingly so no overlap occurs. As an example I had a screenshot saved for the small sizes,

![fb](https://user-images.githubusercontent.com/40718428/74335048-1bdf5400-4dbd-11ea-91d4-fe7ed46acace.png)

EDIT:- Ok I think you are using a different font which is causing the issues and conflicting with some hardcoded spacing values I've used. as bwrsandman said, I think I'd have to look into the spacing properties exposed by ImGUI to make it font independent as well.

**Comment by SadE54** [comment]
Yeah , you're probably right concerning the font size

**Comment by gallickgunner** [comment]
Sorry for the delay but I finally got free time so I'm working on the issue. Be patient :)
