### ISSUE TITLE
Improvements 

### ISSUE THREAD

**Issue by SadE54** [gallickgunner/ImGui-Addons#13]
I started to play with the extension but  I can see several improvement that could be made. It(s just my point , so it could differs from one to another :)

Here's a  Windows 10 file dialog : 
![filebrowser2](https://user-images.githubusercontent.com/2878768/74350387-f3a02700-4db5-11ea-937d-73da24b9db06.png)

The allowed extensions are displayed in a list at the right of the filter in a list after the name filter.
So the names that don't corresponding to the extension pattern are not displayed , so not selectable.

Moreover, adding the classical jokers like '*' to the filter could be an improvement, at least for windows users :)

Finally it should be possible to pass a filename as a string to open the save dialog , to allow acting as a 'save as' with a already existing file

**Comment by gallickgunner** [comment]
Sorry again for the late reply. I'm certainly considering most of the things you said as they definitely are an improvements. I'm also considering to modify the top file bar so users still have a chance to view the whole directory history in case the file bar is too small for long paths.

**Comment by gallickgunner** [comment]
Checkout version 2.0. I've added most of the features and fixed the alignment issue. I'm closing this for now but If there's any problem you can reopen it. Thanks for the feedback and support.
