### ISSUE TITLE
enum value changed

### ISSUE THREAD

**Issue by robertogrossi** [gallickgunner/ImGui-Addons#19]
Thanks for sharing your code.
I think
     ImGuiSelectableFlags_PressedOnClick 
is obsolete (and does not compile with the latest version of ImGUI) and I replaced it with 
     ImGuiSelectableFlags_SelectOnClick
but I am not 100% sure.

Bests
Roberto

**Comment by mattlacey** [comment]
Hit the same issue and made the same fix just now. Looks as though it was a change for Dear ImGui from 1.76 -> 1.77.

**Comment by gallickgunner** [comment]
Sorry for being dead for so long. It's just, I don't feel like doing *anything* xD Anyways thanks for updating me. I still haven't updated it from 1.75. Will take care of it when I do.

**Comment by mattlacey** [comment]
@gallickgunner I don't think anybody would criticize you for feeling that way right now! Look after yourself.

FWIW it was a delight to simply drop this in and have a working file dialog in no time : )

**Comment by gallickgunner** [comment]
All right updated it.

**Comment by robertogrossi** [comment]
Thank you 👍
