### ISSUE TITLE
SELECT folder option

### ISSUE THREAD

**Issue by robertogrossi** [gallickgunner/ImGui-Addons#20]
It would be great for the SELECT folder option to specify also a file filter, so as to get also the list of those filenames contained in the selected folder. Something like this:

file_dialog.showFileDialog("Select Directory##popup", imgui_addons::ImGuiFileBrowser::DialogMode::SELECT, ImVec2(500,300), **".zip,.tgz", &filelist**)

Thanks
-R

**Comment by gallickgunner** [comment]
Hello, I appreciate your ideas but this seems more like a very specific use case. The SELECT option is there to just help the user navigate and select a folder. Trying to return a filtered file list within that selected folder seems extremely limited to a very specific use case. I'd like to keep the addon very simple and stick to its core for now i.e. provide navigation and opening/saving files.

However this isn't a very hard thing to add. If you know ImGui and C++ you can easily fork it and customize it to add all support for these specific use cases. Thanks.

**Comment by robertogrossi** [comment]
Thanks for your reply, I was wondering indeed if this was of general interest. In my case, I can reuse your machinery, e.g., by extending readDIR(), to attain this goal, I will do that. Regards.
