### ISSUE TITLE
Invalid new path if clicking on folder that has same name as a parent or contains part of a parent's name

### ISSUE THREAD

**Issue by CharlieMarcotte** [gallickgunner/ImGui-Addons#21]
Here's a simple fix I made. I haven't tested it thoroughly but it seems to have fix the bug.

```c++
- new_path = current_path.substr(0, current_path.find("/" + current_dirlist[idx]) + current_dirlist[idx].length() + 2 );
+ {
+     new_path = "";
+     for (auto iter = current_dirlist.begin() + 1; iter != current_dirlist.begin() + idx + 1; ++iter)
+         new_path += *iter + "/";
+ }
```

Since there was two folders with the same name in the path, if you navigate to the deepest one by clicking on it the `current_path.find` is going to find the first folder instead.

Example: C:/a/path/to/a/folder

Clicking on the second folder "a" is going to cause the bug. In this case the path is still valid.

Example: C:/app/path/to/a/folder

In that case the new path would be "C:/ap" which does not exist.

**Comment by gallickgunner** [comment]
Hey, nice catch. Can you submit a PR? I actually installed a fresh copy of Windows so I don't have my development environment all set up to check stuff.

Just clear `new_path` at the [start](https://github.com/gallickgunner/ImGui-Addons/blob/f463e293d02fa8dbb972a94a2195fe923ab3b230/FileBrowser/ImGuiFileBrowser.cpp#L673) and note that the `+1` in `current_dirlist.begin() + 1` is only required for the Windows as `"Computer"` is not present in Linux/Mac.

**Comment by gallickgunner** [comment]
Fixed.
