### ISSUE TITLE
Usage example in README missing a call to ImGui::EndMenu()

### ISSUE THREAD

**Issue by skrewby** [gallickgunner/ImGui-Addons#3]
The example code in the README is missing a `ImGui::EndMenu()` after a call to `ImGui::BeingMenu("Menu")`. This was causing the following error when trying to click on the top bar:

> void ImGui::EndMenuBar(): Assertion `window->Flags & ImGuiWindowFlags_MenuBar' failed.

Adding the missing line should make it work again:
```
if(ImGui::BeginMainMenuBar())
{
        if (ImGui::BeginMenu("Menu"))
        {
            if (ImGui::MenuItem("Open", nullptr))
                open = true;
            if (ImGui::MenuItem("Save", nullptr))
                save = true;

            ImGui::EndMenu();
        }
        ImGui::EndMainMenuBar();
}
```

**Comment by gallickgunner** [comment]
Thanks for spotting it :)
