### ISSUE TITLE
ImGui::GetFocusedFocusScope out of date

### ISSUE THREAD

**Issue by bgsa** [gallickgunner/ImGui-Addons#31]
The method ImGui::GetFocusedFocusScope is not found anymore on ImGUI, as well the flag ImGuiSelectableFlags_SelectOnClick.

**Comment by gallickgunner** [comment]
What version are you using? I didn't find any thing related to that in the changelog for 1.81 and 1.82. This one has been updated till 1.80, so if you are still facing problems try using 1.80 perhaps.

**Comment by bgsa** [comment]
I downloaded the latest version of ImGUI from "master" branch about 8 months ago.
I made small changes to fix yout FileBrowser and it did not show any problem.

I changed:
if(show_inputbar_combobox && ( **_ImGui::GetFocusID()_** == focus_scope_id || ImGui::GetCurrentContext()->ActiveIdIsAlive == input_id  ))

and replaced the flag to ImGuiSelectableFlags_PressedOnClick. (the previous flag was not found in "imgui_internal.h").

I hope it helps.
Thanks fou your attetion.
The component is very nice.

**Comment by bgsa** [comment]
Wow... I just checked I am using v1.76 ImGUI version. It seems my library is out of date...

**Comment by bgsa** [comment]
In order to contrib, I created the onClose event.

In header file, in the class, I create a public member:
void (*onClose)();

In .cpp file, the method "closeDialog", added in the end of function:
        if (onClose != nullptr)
            onClose();

One can setup:
file_browser.onClose = &close_function;
