### ISSUE TITLE
Unable to specify folder…

### ISSUE THREAD

**Issue by PhoenixDragosFire** [gallickgunner/ImGui-Addons#34]
Hi GallickRunner,

The dialog window works great! Is there a way to provide the dialog window with a path that would override the default path? There are cases where an application may want to specify a location, based on the context of the operation.  I did attempt to make a tweak, but haven’t been successful.

Peter

**Comment by gallickgunner** [comment]
Hey, thanks for the use. There isn't an option provided but the tweak is really simple. Pass in the path you want to override in the constructor and override the `current_path` variable here [here](https://github.com/gallickgunner/ImGui-Addons/blob/5e274505588665536c7a714b807a17970f9720ee/FileBrowser/ImGuiFileBrowser.cpp#L58).
