### ISSUE TITLE
Problem compiling in Windows

### ISSUE THREAD

**Issue by henriquenunez** [gallickgunner/ImGui-Addons#35]
Hello, I have a program that currently runs on Linux, and I'm porting it to windows too.

I'm trying to use clang++ on windows to build it, but it gives me an error:

The command used to build is the following:

`clang++ -c --std=c++17 ../ImGui-Addons/FileBrowser/ImGuiFileBrowser.cpp -I../ImGui-Addons/imgui -o filebrowser.o`

(My makefile was not working, so i'm doing this at the moment)

It gives me the errors:

```
../ImGui-Addons/FileBrowser/ImGuiFileBrowser.cpp:589:47: error: no member named 'GetFocusScopeID' in namespace 'ImGui'; did you mean
      'GetFocusScope'?
        if(show_inputbar_combobox && ( ImGui::GetFocusScopeID() == focus_scope_id || ImGui::GetCurrentContext()->ActiveIdIsAliv...      
                                       ~~~~~~~^~~~~~~~~~~~~~~
                                              GetFocusScope
../ImGui-Addons/imgui\imgui_internal.h:2276:29: note: 'GetFocusScope' declared here
    inline ImGuiID          GetFocusScope()                 { ImGuiContext& g = *GImGui; return g.CurrentWindow->DC.NavFocusScop...     
                            ^
../ImGui-Addons/FileBrowser/ImGuiFileBrowser.cpp:614:113: error: use of undeclared identifier 'ImGuiSelectableFlags_PressedOnClick'; did
      you mean 'ImGuiSelectableFlags_SelectOnClick'?
  ...false, ImGuiSelectableFlags_NoHoldingActiveID | ImGuiSelectableFlags_PressedOnClick))
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                     ImGuiSelectableFlags_SelectOnClick
../ImGui-Addons/imgui\imgui_internal.h:728:5: note: 'ImGuiSelectableFlags_SelectOnClick' declared here
    ImGuiSelectableFlags_SelectOnClick          = 1 << 21,  // Override button behavior to react on Click (default is Click+Release)  
```

Can someone give me some help?

**Comment by gallickgunner** [comment]
I think this is related to #31 . You prolly downloaded the latest or pulled the master version of imgui directly right? The problem is imgui internal functions keep changing so I have to manually update it every time there is a change. I haven't updated it to the latest version yet. Try using v1.80. 

As a friendly reminder always pull repos recursively so you get the compatible version of the submodules.
