### ISSUE TITLE
Other imgui items not working when selecting path

### ISSUE THREAD

**Issue by 0z0sk0** [gallickgunner/ImGui-Addons#46]
Windows 8.1 x64
Microsoft Visual Studio 2022 C++17
ImGui v.1.86

Other imgui items not working when selecting path

**Comment by 0z0sk0** [comment]
FileBrowser just pause the thread with ImGui Render

**Comment by gallickgunner** [comment]
Sorry can you be a bit more specific? What do you mean by other imgui items not working? And I don't get what do you mean by pausing the thread with Render?
