### ISSUE TITLE
Remember the last opened path

### ISSUE THREAD

**Issue by neon5d** [gallickgunner/ImGui-Addons#47]
Hello,

Currently, the initial path looks based on the current path.
Is there any way to set the last opened path as the initial path?
Thank you

**Comment by gallickgunner** [comment]
Yes. See [this ](https://github.com/gallickgunner/ImGui-Addons/blob/75be5bce10d203c0b882c45446e9aba04251c64e/FileBrowser/ImGuiFileBrowser.cpp#L1221) function.
Set the current path variable to the selected path if it's not empty.

**Comment by neon5d** [comment]
Thank you for the information.
It seems I need some work to save and retrieve the directory path from imgui.ini.
If it is integrated as an option, it would be great.
Thank you.
