### ISSUE TITLE
Option (or function) to select All valid files when open file

### ISSUE THREAD

**Issue by georgemoralis** [gallickgunner/ImGui-Addons#48]
A function maybe to be able to render Open file with "All valid Files" as default option

**Comment by gallickgunner** [comment]
It's already there. If you provide a list of extension, then All Valid Files option appears automatically together with all the extensions you provided

**Comment by georgemoralis** [comment]
I want to be able to have pre selected the all valid option when I open dialog

**Comment by gallickgunner** [comment]
> I want to be able to have pre selected the all valid option when I open dialog

Then you need to just set the `selected_ext_idx` variable to whatever index the All valid option has.
