### ISSUE TITLE
Allowing any files on subsequent file dialogs after using "All valid files"

### ISSUE THREAD

**Issue by Jared-Swislow-HaptX** [gallickgunner/ImGui-Addons#54]
After the file dialog is used once and a file is selected with the option "All valid files," the next file dialog opened will have the first extension selected, but will allow all files to be selected. The problem persists on future file dialogs until another extension is selected on the drop down

## Steps to reproduce

1. Open a file dialog
2. Select "All valid files"
3. Select any file
4. Open another file dialog. Now the first extension will be selected, but all files will be listed and able to be selected

Like I said, it goes back to normal after the user selects an extension from the dropdown

**Comment by gallickgunner** [comment]
It seems I missed a `show_all_valid_files = false` in [closeFileDialog](https://github.com/gallickgunner/ImGui-Addons/blob/f5f95b7e1e08a489087b8c1e901f8fccd5f14f34/FileBrowser/ImGuiFileBrowser.cpp#LL86C28-L86C39). Hence it remembers the previous selection even after you close the first one.

Adding that will hopefull fix the issue. Can you test it submit a PR. Thanks

**Comment by Jared-Swislow-HaptX** [comment]
Yep, that fixed it. Thanks!
