### ISSUE TITLE
In visual studio there are issues related to the macro `max` and `min`

### ISSUE THREAD

**Issue by bwrsandman** [gallickgunner/ImGui-Addons#7]
They should be undefined `imguifilebrowser.cpp`

**Comment by gallickgunner** [comment]
Nice find. I think I was using MinGW-w64 and it already defines `NOMINMAX` hence I didn't realize it. Fixed with commit [652667c](https://github.com/gallickgunner/ImGui-Addons/commit/652667c25bb03693046be4d7af63560d8476826c)
